@setlocal EnableDelayedExpansion
@set "a=%1"
@set /a b=%2&rem
@set /a c=%3&rem
@set /a d=%b%*%c%
@echo !a:~%d%,%c%!
@endlocal
@exit /b

::
:: This batch file helps with finding certain substrings
::
:: Auto-generated by draw_batch.bat
::
